name: API Test Runner

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  track_shoplifting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tracking script
        run: python api_test.py

      - name: Commit and push changes
        run: |
          git config --global user.email "bbkilla@gmail.com"
          git config --global user.name "GitHub Actions"
          git add status_history.json
          git commit -m "upsate status_history.json"
          git push
