name: API Test Runner

on:
  workflow_dispatch:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  test_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run API test
        run: python api_test.py
